fuse: add -fno-strict-aliasing flag
Because of:
src/pmemfile-fuse/main.c: In function ‘pmemfile_fuse_readdir’:
src/pmemfile-fuse/main.c:146:4: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
    unsigned long nextoff = *(unsigned long *)&dirp[i];
    ^
src/pmemfile-fuse/main.c:149:4: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
    unsigned short reclen = *(unsigned short *)&dirp[i];
    ^